zeebe:
  client:
    # local Camunda distro
    broker.gatewayAddress: 127.0.0.1:26500
    security.plaintext: true
    # enable Camunda Spring client
    enabled: true

camunda:
  operate:
    client:
      # try to disable Operate client but not working
      enabled: false
      # reduce retry time of Operate client to fail faster
      startup:
        retry:
          maxAttempts: 1
          awaitDurationInSeconds: 0
# try to disable nested inbound connector beans but not working
#  connector:
#    polling:
#      enabled: false
#    webhook:
#      enabled: false


